name: Phantom
version: ${project.version}
main: org.phantomapi.Phantom
description: ${project.description}
author: cyberpwn
authors: [cyberpwn]
softdepend: [Citizens, FastAsyncWorldEdit, WorldEdit, Vault, ProtocolLib]
website: http://phantomapi.org/
load: POSTWORLD
database: false
commands:
  phantom:
    aliases: [ph, p, phan, pha, nova, nov, wraith, wra, wr, ghost, gh]
    description: The only damn command you need
  phast:
    aliases: [phst]
    description: Phast scripting
  crash:
    description: Crash a given player